### ISSUE TITLE
java.lang.ClassCastException: mod.chiselsandbits.chiseledblock.TileEntityBlockChiseled cannot be cast to gcewing.architecture.ShapeTE

### ISSUE THREAD

**Issue by miiichael** [wooky/architecturecraft#3]
Hello, I'm aware I'm possibly blaming the wrong mod (I'm mindful that it could potentially be a C&B bug instead), but I do need to start somewhere. :stuck_out_tongue: 

Backtrace:
```java.lang.ClassCastException: mod.chiselsandbits.chiseledblock.TileEntityBlockChiseled cannot be cast to gcewing.architecture.ShapeTE
        at gcewing.architecture.ShapeBlock.getLocalBounds(ShapeBlock.java:152)
        at gcewing.architecture.ShapeBlock.func_185496_a(ShapeBlock.java:109)
        at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_185900_c(BlockStateContainer.java:454)
        at net.minecraft.block.Block.func_180646_a(Block.java:375)
        at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_185890_d(BlockStateContainer.java:435)
        at net.minecraft.world.World.func_175716_a(World.java:3160)
        at net.minecraft.item.ItemBlock.func_179222_a(ItemBlock.java:125)
        at net.minecraft.client.multiplayer.PlayerControllerMP.func_187099_a(PlayerControllerMP.java:418)
        at PlayerControllerOF.func_187099_a(PlayerControllerOF.java:88)
        at net.minecraft.client.Minecraft.func_147121_ag(Minecraft.java:1518)
        at net.minecraft.client.Minecraft.redirect$onRightClickMouse$0(Minecraft.java:146)
        at net.minecraft.client.Minecraft.func_184117_aA(Minecraft.java:2184)
        at net.minecraft.client.Minecraft.func_184118_az(Minecraft.java:1961)
        at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1749)
        at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1055)
        at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:371)
        at net.minecraft.client.main.Main.main(SourceFile:124)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
        at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
```
Or read the full [crash-2016-12-04_19.35.56-client.txt](https://github.com/wooky/architecturecraft/files/629437/crash-2016-12-04_19.35.56-client.txt)

Hopefully a screenshot will help illustrate what I was doing at the time:
![2016-12-04_19 44 16](https://cloud.githubusercontent.com/assets/4179353/20865927/294521aa-ba5a-11e6-977d-e8a458f113bc.png)

I'm holding some regular AC window frames, made from regular oak. What I suspect is supposed to happen is nothing, because I haven't sawed these window frames in half to fit the available space...

The house itself is made from stone, that's been Chisel'ed into the brick pattern you see, and then cut using a Chisels & Bits saw into smaller blocks.

If required, I can (eventually) throw together an instance with just the three mods in question (and to determine whether Chisel is actually part of the equation), but obviously I'm hoping to avoid that...

**Comment by wooky** [comment]
Please try the official version of ArchitectureCraft: http://www.cosc.canterbury.ac.nz/greg.ewing/minecraft/mods/ArchitectureCraft/. If the same problem occurs, contact that developer.

This is the unofficial version, and quite frankly, was never supported.

**Comment by miiichael** [comment]
Err, I grabbed it from [curseforge](https://minecraft.curseforge.com/projects/architecturecraft/files/2344384), so I thought I already was using an official version!

**Comment by wooky** [comment]
You're right, that is the official version. However, this repo is the unofficial version, which was made long before the official one released. Basically, I'm not the original author of this mod, so I can't help you with the bug.

**Comment by miiichael** [comment]
Ohhh, so I've merely reported the bug in the wrong place, rather than installed the wrong version. :stuck_out_tongue: 

Sorry for the confusion!
